ccflags-$(CONFIG_MTK_PLATFORM) += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-$(CONFIG_MTK_PLATFORM) += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
obj-$(CONFIG_OPLUS_DEVICE_INFO)	+=  device_info.o
