# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_OPROJECT) 	+= oplus_project.o
obj-y		+= oplus_keventupload/
obj-y		+= feedback/
obj-$(CONFIG_OPLUS_FEATURE_MM_FEEDBACK)		+= oplus_mm_fb/
obj-$(CONFIG_NANDSWAP)		+= oplus_nandswap/
