# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_DUMP_DEVICE_INFO)	+=  dump_device_info.o
obj-$(CONFIG_OPLUS_FEATURE_OPROJECT) 	+= oplus_project.o
obj-$(CONFIG_FG_TASK_UID)  +=  fg_uid.o
obj-y		+= oplus_keventupload/
obj-y		+= feedback/
obj-y     += device_info/
obj-y     += network/
obj-$(CONFIG_OPLUS_ION_BOOSTPOOL) += ion_boost_pool/oplus_ion_boost_pool.o
obj-$(CONFIG_OPLUS_FEATURE_MM_FEEDBACK)		+= oplus_mm_fb/
obj-$(CONFIG_NANDSWAP)		+= oplus_nandswap/
